2-FavoritePhoto-2/2-FavoritePhoto-2-BE

- http/shop.http
- src/app.ts
- src/containers/shop.container.ts
- src/controllers/shop.controller.ts
- src/repositories/shop.repository.ts
- src/routes/shop.route.ts
- src/services/shop.service.ts
추가 기능: getShopList, creatShop, getShopById, updateShop, deleteShop
> [김영은] Feat: Add CRUD for shop

- .gitignore
- http/auth.http
- http/shop.http
- package-lock.json
- package.json
- prisma/migrations/20241121020835_init/migration.sql
- prisma/schema.prisma
- src/app.ts
- src/containers/auth.container.ts
- src/containers/shop.container.ts
- src/controllers/auth.controller.ts
- src/controllers/shop.controller.ts
- src/repositories/auth.repository.ts
- src/repositories/shop.repository.ts
- src/routes/auth.route.ts
- src/routes/shop.route.ts
- src/services/auth.service.ts
- src/utils/verifyAuth.ts
로그인, 회원가입, 토큰 재발급 구현 완료!
+ 현재까지 진행된 POST, PATCH, DELETE에 인가 추가 완료
> [김영은] Feat: Add signup, login, refreshToken

- src/repositories/shop.repository.ts
- src/routes/auth.route.ts
- src/routes/shop.route.ts
- src/services/auth.service.ts
프론트엔드 수정사항 반영합니다.
- 엑세스토큰 만료시간 1시간 -> 24시간
- 엔드포인트 /shop/cards/:shopId -> /shop/:shopId
- 판매 상세 조회 데이터에 카드 및 판매자 정보 추가
> [김영은] Fix: Change in accessToken, auth endpoint, getShopById

- src/controllers/shop.controller.ts
- src/repositories/shop.repository.ts
- src/services/shop.service.ts
요청사항:  shop 목록 조회 시 현재 보고 있는 shop을 제외할 수 있게 수정
프론트엔드에서 요청한 수정사항 반영했습니다.
> [김영은] Feat: Add exclude query on getShopList

- .prettierrc
- package-lock.json
- package.json
- prisma/seed.ts
- src/app.ts
- src/controllers/auth.controller.ts
- src/controllers/shop.controller.ts
- src/routes/auth.route.ts
- src/routes/shop.route.ts
- src/utils/errors.ts
- asyncHandler 적용
- errorHandler 수정
- seeding 속도 높이기위해 seed.ts 수정
> [김영은] Refactor: Modify common modules

- http/user.http
- package-lock.json
- prisma/migrations/20241122152251_init/migration.sql
- src/controllers/user.controller.ts
- src/repositories/user.repository.ts
- src/routes/user.route.ts
- src/services/user.service.ts
- 유저 포토카드 전체 조회
- 프로필 조회도 로그인시 가능하게 변경
> [이동훈] Feat: User photo cards

- http/exchange.http
- mock/mock.ts
- package-lock.json
- prisma/migrations/20241122002435_exchange_and_shop_relation/migration.sql
- prisma/migrations/20241125072719_update_card_shop_quantity_field/migration.sql
- prisma/migrations/20241125073033_update_card_shop_quantity_field_optional/migration.sql
- prisma/schema.prisma
- src/app.ts
- src/containers/exchange.container.ts
- src/controllers/exchange.controller.ts
- src/repositories/exchange.repository.ts
- src/routes/exchange.route.ts
- src/services/exchange.service.ts
createExchange, acceptExchange, refuseExchange, cancelExchange 기본적인 기능 구현
- createExchange : 교환 제안 생성
- acceptExchange : 판매등록된 카드와 제안한 카드 수량 감소, seller와 buyer에게 교환되는 카드생성(카드가 존재하면 수량증가 미구현)
- refuseExchange : sellerId로 권한 인증 후 교환 삭제
- cancelExchange : buyerId로 권한 인증 후 교환 삭제
> [강명곤]Feature/exchange offer

- src/controllers/shop.controller.ts
- src/services/shop.service.ts
> [김영은] Feat: Add query to get shop list by userId

- http/user.http
- src/controllers/user.controller.ts
- src/repositories/user.repository.ts
- src/routes/user.route.ts
- src/services/user.service.ts
어제 유림님이 요청한 내 판매 포토카드 전체 조회 API 입니다.
(상점에 등록한 내 카드 + 교환 신청(제시)한 내 카드)
> [김영은] Feat: Add getMyCardsOnSale

- http/user.http
- mock/mock.ts
- src/repositories/user.repository.ts
- 기존의 교환 제시 카드의 description이 교환 제시 내용이 아닌 card의 description이 표기되어 이를 수정
- 그 외 response값 필요한 값만 나오게 수정
> [이동훈] Fix: Excahnge list response value modified

- src/repositories/user.repository.ts
- 투자가 아무것도 없을경우 에러처리되는것을 빈 배열이 나오게 수정했습니다.
> [이동훈] Refactor: Empty exchange list to empty array

- http/shop.http
- http/user.http
- src/repositories/user.repository.ts
- src/services/shop.service.ts
- src/services/user.service.ts
- shop의 전체리스트 조회에서 keyword가 name만 할수있게 변경
- user의 나의 카드 전체리스트 조회에서 keyword가 name만 할수있게 변경
- user의 나의 판매중인 카드 조회에서 keyword가 name만 할수있게 변경
> [이동훈] Feat: keyword function delete description

- .prettierrc
prettier 설정 변경: useTabs: true -> 삭제
> [김영은] Style: Remove useTabs setting on .prettierrc

- src/repositories/user.repository.ts
- exchange response에 exchangeId를 추가했습니다
> [이동훈] Fix: Exchange list response add exchangeId

- src/app.ts
CORS 설정 변경:
- 브라우저의 쿠키 사용을 위한 credentials 설정 활성화
- 일단 origin은 모두 허용으로 설정
> [김영은] Feat: Enale CORS credentials

- src/repositories/auth.repository.ts
- src/services/auth.service.ts
> [김영은] Fix: Add invalid nickname error

- package-lock.json
> [김영은] Fix: install multer, s3, etc... for createCard

- prisma/structs.ts
> [강명곤]Fix:Update structs.ts

- src/controllers/points.controller.ts
- src/repositories/points.repository.ts
- src/repositories/user.repository.ts
- src/routes/points.route.ts
- src/services/points.service.ts
- src/utils/errors.ts
- pointLog 조회 (추가적으로 만들어 봤습니다)
- 페이지네이션 기능
- action필드 필터링 기능
- 기간별 필터링 기능
- 정렬 기능
- 신철님께서 교환 제시한 포토 카드 목록 조회 시 교환 완료된 데이터 빼고 교환 요청 중인 데이터만 요청하셔서 user.repository에서 getExchangesByShopId 조건에 complete: false 추가하였습니다. (간단한거라 같이 해서 올립니다.)
> [강명곤]Feature/get pointlogs

- src/controllers/exchange.controller.ts
- src/routes/exchange.route.ts
exchange에서 try-catch 삭제 및 asyncHandler 설정
> [강명곤]Refactor:  Replace try-catch with asyncHandler in Exchange

- src/controllers/user.controller.ts
- asyncHandler사용을 통해 try-catch 삭제
> [이동훈] Refactor: Use async-handler for delete try-catch

- package-lock.json
- package.json
- prisma/schema.prisma
- src/app.ts
- src/swagger/swagger.yaml
- tsconfig.json
swagger ui 세팅하고 예시를 넣었습니다.
- 예시를 보면서 paths를 각각 추가하시면 됩니다.
- 서버 켜고 `/api` 에서 확인하면서 작성하시고 테스트 하세요 :)
- 하단에 schema도 수정 추가해야 합니다.
- 그래서 schema를 먼저 다 정리하고 진행을 해야 할 것 같습니다.
> [김영은] Feat: Add swagger example

- prisma/structs.ts
- src/controllers/exchange.controller.ts
exchange.controller - createExchange에 적용
> [강명곤]Feat: Apply exchange structs

- http/exchange.http
- package-lock.json
- src/services/exchange.service.ts
이미 승인된 교환제안(complete=true)이면 승인, 거절, 취소 시 에러 추가
> [강명곤]Fix: add approved exchange validation

- src/controllers/user.controller.ts
- src/services/user.service.ts
> [이동훈] Refactor: Create card struct

- src/swagger/swagger.yaml
- securitySchemes에 bearerAuth추가
> [이동훈] Feat: add bearer Auth

- src/repositories/shop.repository.ts
- src/services/shop.service.ts
> [김영은] Fix: Remove unnecessary logic

- http/user.http
- src/repositories/user.repository.ts
> [이동훈] Feat: Card detail add card id

- README.md
> [김영은] Docs: Add initial readme

- src/controllers/auth.controller.ts
> [김영은] Perf: Modify cookie secure setting

- http/user.http
- src/swagger/swagger.yaml
> [이동훈] Feat: user swagger

- mock/mock.ts
> [강명곤]Chore: Fix some mockdata image

- src/utils/errorHandler.ts
- src/utils/errors.ts
예를 들어,
throw new AppError('구매자의 카드 정보를 찾을 수 없습니다.', 404);
이런 형식으로 수정해 주시면 됩니다!
> [김영은] Fix: Add common error class

- README.md
> [이동훈] Feat: update readme user function

- http/user.http
- src/app.ts
- src/repositories/user.repository.ts
- src/services/user.service.ts
- src/swagger/swagger.yaml
> [이동훈] Feat: user error handler
